# Generated by Django 4.2 on 2023-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('MED', 'Médico'), ('REG', 'Regulador'), ('PAT', 'Paciente')], default='PAT', max_length=3, verbose_name='Tipo de usuário'),
        ),
    ]
