# Generated by Django 4.2 on 2023-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nome completo'),
        ),
    ]
