# Generated by Django 4.2 on 2023-04-09 22:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid10',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('letter', models.CharField(editable=False, max_length=1, verbose_name='Letra')),
                ('number', models.CharField(editable=False, max_length=3, verbose_name='Número')),
                ('description', models.CharField(editable=False, max_length=200, verbose_name='Descrição')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Homem'), ('W', 'Mulher')], editable=False, max_length=1, verbose_name='Sexo relacionado')),
                ('cause_death', models.BooleanField(blank=True, editable=False, max_length=1, verbose_name='Sexo relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('specialty', models.CharField(max_length=200, verbose_name='Especialidade')),
                ('requester_text', models.TextField(verbose_name='Solicitação')),
                ('responder_text', models.TextField(verbose_name='Resposta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Está respondido?')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_patient', to='users.profile', verbose_name='Paciente')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_requester', to='users.profile', verbose_name='Solicitante')),
                ('requester_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_requester', to='consultations.cid10', verbose_name='Hipótese/diagnóstico')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_responder', to='users.profile', verbose_name='Respondente')),
                ('responder_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_responder', to='consultations.cid10', verbose_name='Hipótese/diagnóstico')),
            ],
        ),
    ]
